Fix #1469 Use a different checksum calculation method to run in FIPS env
jschneier/django-storages pull request #1473
Opened 2024-11-15 13:22 UTC by markesha

Python 3.10 and later versions rely on OpenSSL 1.1.1 or newer, which includes FIPS-compliance checks.

MD5 is not an approved algorithm in FIPS mode, so attempting to instantiate self.blob.download_to_file(self._file) will fail when the system is running in FIPS mode.

The change configures the `download_to_file` function to use an alternative algorithm provided by gcloud storage SDK - 'crc32c' - for checksum calculation.

2024-11-15 14:22 UTC, jschneier commented
Just making sure, this change is backwards compatible, right?

2024-11-18 10:59 UTC, markesha commented
@jschneier the change depends on a specific version of the google storage lib, that I'm locking with the change. All the test python versions were already using the latest one 2.18.2, e.g. see 3.7 logs:

```py3.7-django3.2: apache-libcloud==3.8.0,asgiref==3.7.2,azure-core==1.30.1,azure-storage-blob==12.19.1,bcrypt==4.2.0,boto3==1.33.13,botocore==1.33.13,cachetools==5.5.0,certifi==2024.8.30,cffi==1.15.1,charset-normalizer==3.4.0,coverage==7.2.7,cryptography==43.0.3,Django==3.2.25,django-storages @ file:///home/runner/work/django-storages/django-storages/.tox/.tmp/package/1/django-storages-1.14.4.tar.gz#sha256=fd2920db03cfb63bf4d6f600ee0e6bdb668931505a261c3f0107cda7e5947bc8,dropbox==12.0.2,exceptiongroup==1.2.2,google-api-core==2.23.0,google-auth==2.36.0,google-cloud-core==2.4.1,google-cloud-storage==**2.18.2**,```

I guess it should be compatible.

2024-11-19 10:39 UTC, markesha commented
@jschneier the failing test `tests/test_gcloud.py::GoogleCloudGzipClientTests::test_storage_save_gzipped` appears unrelated to the change and also fails on earlier revisions.

```
 AssertionError: expected call not found.
 Expected: upload_from_file(<ANY>, rewind=True, retry=<google.api_core.retry.retry_unary.Retry object at 0x10dad5300>, size=11, predefined_acl=None, content_type='application/javascript')
 Actual: upload_from_file(<ContentFile: Raw content>, rewind=True, retry=<google.api_core.retry.retry_unary.Retry object at 0x10dad5300>, size=11, predefined_acl=None, content_type='text/javascript')
```

2024-11-22 05:53 UTC, jschneier commented
@markesha any idea what's going on here? There are no failures now but the tests were never "fixed".

2024-11-22 05:53 UTC, jschneier requested changes
Looks good although I don't understand the test reality.

2024-11-22 05:53 UTC, jschneier commented on pyproject.toml
> +  "google-cloud-storage>=1.31",
Can you actually change this to be `>=1.32`. Turns out we already require that due to the retry import.

2024-11-22 09:20 UTC, markesha commented
@jschneier I'm not sure what's happening - it still fails locally for me

2024-11-23 03:37 UTC, jschneier commented
> @jschneier I'm not sure what's happening - it still fails locally for me

Well, in #1476 I just change it to use CSS which should fix whatever weird mimetype problem we are having.

2024-11-28 00:26 UTC, jschneier approved these changes

2024-11-28 00:28 UTC, merged

2025-01-03 12:47 UTC, markesha commented
@jschneier Do you mind making a release for this change?